### ISSUE TITLE
希望vue-cesium2.x能够同步3.x的新功能

### ISSUE THREAD

**Issue by 912419804** [zouyaoji/zouyaoji#1]
目前很多项目还在使用vue2.x，所以希望可以同步一下3.x的功能，万分感谢！

**Comment by zouyaoji** [comment]
这个可能不太好办啊，设计思路都不一样的了。

**Comment by zouyaoji** [comment]
目前vue2版本只改缺陷了哈。

**Comment by zouyaoji** [comment]
@912419804 
或者你列一下 你对vue3版本的哪些组件有迁移到vue2版本的需求？ 我这边只把能迁移的迁移一下。

**Comment by 912419804** [comment]
非常感谢！目前希望优先同步绘制和测量等基础能力，并希望测量能够支持方位角测量！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 上午10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zouyaoji/zouyaoji] 希望vue-cesium2.x能够同步3.x的新功能 (Issue #1)




 
@912419804
 或者你列一下 你对vue3版本的哪些组件有迁移到vue2版本的需求？ 我这边只把能迁移的迁移一下。

**Comment by zouyaoji** [comment]
这个恐怕要让你失望咯，绘制和测量那部分是基于vue3的特性完全重构了的，不好搞到vue2。~~
还是等新项目来了上vue3版本的吧。

我目前计划把vue3版本里面的一些图层组件如腾讯、高德这些迁移到vue2。
然后方位测量有没有例子看看？

**Comment by 912419804** [comment]
好吧~_~&nbsp;
https://dc.dvgis.cn/#/editor?type=analysis&amp;example=measure
您看一下这个DC的实现效果，另外mars3d也有相关实现，就是我现在是在手机上看东西，不好找了





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zouyaoji/zouyaoji] 希望vue-cesium2.x能够同步3.x的新功能 (Issue #1)




 
这个恐怕要让你失望咯，绘制和测量那部分是基于vue3的特性完全重构了的，不好搞到vue2。~~
 还是等新项目来了上vue3版本的吧。
 
我目前计划把vue3版本里面的一些图层组件如腾讯、高德这些迁移到vue2。
 然后方位测量有没有例子看看？

**Comment by zouyaoji** [comment]
好的哈~
